### ISSUE TITLE
Implement in D

### ISSUE THREAD

**Issue by funny-falcon** [facebookarchive/dfuse#2]
Looks like both Go fuse libraries chooses to re-implement FUSE protocol in pure Go:
https://github.com/hanwen/go-fuse
https://github.com/bazillion/fuse
It is clear that they choose to do this way cause Go has purer C interoperability.

But still, did you consider to implement FUSE in D instead of wrapping libfuse?

**Comment by dsp** [comment]
This is an interesting thought. However I think at the moment we rather rely on the libfuse as it is stable and well understood. Unlike Go we don't have get much performance penalties when calling into C or getting called from C as D's execution model is compatible with C and doesn't require a stack rewrite. So for the moment I don't see much of a benefit to reimplementing the whole protocol.

**Comment by ghost** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by dsp** [comment]
I think we can close this out. While I appreciate the general idea, I think going with fuse bindings, in particular as D follows C calling conventions (unlike GO), makes sense.
