### ISSUE TITLE
Put library on dub registry.

### ISSUE THREAD

**Issue by FreeSlave** [facebookarchive/dfuse#4]
Could you register library as dub package? http://code.dlang.org/

Although it seems that anyone can add packages, I would better to ask author first.

**Comment by extrawurst** [comment]
afaik everyone can do that

**Comment by dsp** [comment]
Feel free to do it, if not I can take a look. It's for sure a good idea to do.

**Comment by FreeSlave** [comment]
I've encountered some issues with declarations translated from C to D (for example wrong declarations of bitfields). Should fix this first and ensure it works.

**Comment by extrawurst** [comment]
it's done: http://code.dlang.org/packages/dfuse
issue can be closed

**Comment by dsp** [comment]
cool thanks again for that!
